import { pendingLinguisticReview } from "@/content/review-state";
import type { Character } from "@/domain/content/types";

export const characters = [
  {
    ...pendingLinguisticReview,
    id: "character-abu-dhabi-cafe-mariam",
    destinationId: "destination-abu-dhabi",
    targetDialectId: "emirati-abu-dhabi",
    displayName: { en: "Mariam", ar: "مريم" },
    role: "local_character",
    learnerLevel: "beginner",
    ageContext: "young adult café host",
    relationship: "welcoming host meeting the learner for the first time",
    personality: "calm, observant, and warmly efficient",
    voiceProfile: { locale: "ar-AE", preferredGender: "female" },
    visualAssetPath: "/characters/abu-dhabi-cafe-mariam-refined-v3.webp",
    visualId: "mariam-cafe",
  },
  {
    ...pendingLinguisticReview,
    id: "character-abu-dhabi-campus-zayed",
    destinationId: "destination-abu-dhabi",
    targetDialectId: "emirati-abu-dhabi",
    displayName: { en: "Zayed", ar: "زايد" },
    role: "local_character",
    learnerLevel: "beginner",
    ageContext: "university student",
    relationship: "a peer helping a new student",
    personality: "open, upbeat, and quick to point the way",
    voiceProfile: { locale: "ar-AE", preferredGender: "male" },
    visualAssetPath: "/characters/abu-dhabi-campus-zayed-refined-v1.webp",
    visualId: "zayed-campus",
  },
  {
    ...pendingLinguisticReview,
    id: "character-cairo-cafe-nour",
    destinationId: "destination-cairo",
    targetDialectId: "egyptian-cairo",
    displayName: { en: "Nour", ar: "نور" },
    role: "local_character",
    learnerLevel: "beginner",
    ageContext: "young adult café host",
    relationship: "a neighbourhood café host meeting a customer",
    personality: "bright, attentive, and gently playful",
    voiceProfile: { locale: "ar-EG", preferredGender: "female" },
    visualAssetPath: "/characters/cairo-cafe-nour-refined-v1.webp",
    visualId: "nour-cafe",
  },
  {
    ...pendingLinguisticReview,
    id: "character-cairo-taxi-hossam",
    destinationId: "destination-cairo",
    targetDialectId: "egyptian-cairo",
    displayName: { en: "Hossam", ar: "حسام" },
    role: "local_character",
    learnerLevel: "beginner",
    ageContext: "middle-aged taxi driver",
    relationship: "a driver taking the learner across the city",
    personality: "direct, patient, and focused on the road",
    voiceProfile: { locale: "ar-EG", preferredGender: "male" },
    visualAssetPath: "/characters/cairo-taxi-hossam-refined-v1.webp",
    visualId: "hossam-taxi",
  },
] as const satisfies readonly Character[];
