import { pendingLinguisticReview } from "@/content/review-state";
import type {
  CrossDialectTransferRule,
  DialectVariant,
  LearningConcept,
} from "@/domain/content/types";

export const learningConcepts = [
  {
    ...pendingLinguisticReview,
    id: "concept-greeting",
    intent: "greet_person",
    meaningEn: "Open a brief everyday interaction politely.",
    variantIds: [],
  },
  {
    ...pendingLinguisticReview,
    id: "concept-order-coffee",
    intent: "order_coffee",
    meaningEn: "Request coffee in a casual café interaction.",
    variantIds: [
      "variant-egyptian-want-coffee",
      "variant-emirati-want-coffee",
      "variant-msa-want-coffee",
    ],
  },
  {
    ...pendingLinguisticReview,
    id: "concept-drink-detail",
    intent: "specify_drink_detail",
    meaningEn: "Choose a drink temperature, size, sugar, milk, or location detail.",
    variantIds: [],
  },
  {
    ...pendingLinguisticReview,
    id: "concept-introduce-self",
    intent: "introduce_self",
    meaningEn: "Give a short personal introduction to a peer.",
    variantIds: [],
  },
  {
    ...pendingLinguisticReview,
    id: "concept-find-place",
    intent: "ask_for_location",
    meaningEn: "Ask where a place or building is.",
    variantIds: [],
  },
  {
    ...pendingLinguisticReview,
    id: "concept-class-time",
    intent: "state_class_time",
    meaningEn: "Say when a class begins.",
    variantIds: [],
  },
  {
    ...pendingLinguisticReview,
    id: "concept-study-subject",
    intent: "state_study_subject",
    meaningEn: "Name a subject or field of study.",
    variantIds: [],
  },
  {
    ...pendingLinguisticReview,
    id: "concept-state-destination",
    intent: "state_destination",
    meaningEn: "Tell a driver the intended destination.",
    variantIds: [],
  },
  {
    ...pendingLinguisticReview,
    id: "concept-choose-route",
    intent: "choose_route",
    meaningEn: "Choose between proposed routes.",
    variantIds: [],
  },
  {
    ...pendingLinguisticReview,
    id: "concept-describe-urgency",
    intent: "describe_urgency",
    meaningEn: "Say whether the journey is urgent.",
    variantIds: [],
  },
  {
    ...pendingLinguisticReview,
    id: "concept-confirm-stop",
    intent: "confirm_stop",
    meaningEn: "Confirm where the driver should stop.",
    variantIds: [],
  },
  {
    ...pendingLinguisticReview,
    id: "concept-understand-price",
    intent: "acknowledge_price",
    meaningEn: "Acknowledge a stated fare or price.",
    variantIds: [],
  },
  {
    ...pendingLinguisticReview,
    id: "concept-polite-close",
    intent: "close_interaction",
    meaningEn: "Thank the other person and close a short interaction.",
    variantIds: [],
  },
] as const satisfies readonly LearningConcept[];

export const dialectVariants = [
  {
    ...pendingLinguisticReview,
    id: "variant-egyptian-want-coffee",
    conceptId: "concept-order-coffee",
    dialectId: "egyptian-cairo",
    surfaceAr: "عايز قهوة",
    matchForms: ["عايز قهوة", "عايز قهوة لو سمحت"],
    glossEn: "I want coffee.",
    register: "casual",
    communicativeIntent: "order_coffee",
    locality: "Cairo café context",
    linguisticNotes: "Prototype candidate for a casual Cairene café request.",
    reviewerNote: "Confirm current Cairene naturalness, politeness, and speaker-gender bounds.",
    scenarioIds: ["scenario-cairo-cafe", "scenario-abu-dhabi-cafe"],
    publicationStatus: "disabled",
  },
  {
    ...pendingLinguisticReview,
    id: "variant-emirati-want-coffee",
    conceptId: "concept-order-coffee",
    dialectId: "emirati-abu-dhabi",
    surfaceAr: "أبغي قهوة",
    matchForms: ["أبغي قهوة", "أبغي قهوة لو سمحت"],
    glossEn: "I want coffee.",
    register: "casual",
    communicativeIntent: "order_coffee",
    locality: "Abu Dhabi café context",
    linguisticNotes: "Prototype candidate for a casual Emirati café request.",
    reviewerNote: "Confirm contemporary Abu Dhabi usage, register, and whether a narrower speaker bound is needed.",
    scenarioIds: ["scenario-abu-dhabi-cafe"],
    publicationStatus: "disabled",
  },
  {
    ...pendingLinguisticReview,
    id: "variant-msa-want-coffee",
    conceptId: "concept-order-coffee",
    dialectId: "msa-modern-standard",
    surfaceAr: "أريد قهوة",
    matchForms: ["أريد قهوة", "أريد قهوة من فضلك"],
    glossEn: "I want coffee.",
    register: "formal",
    communicativeIntent: "order_coffee",
    locality: "Formal Arabic bridge for casual café contexts",
    linguisticNotes: "Prototype MSA-to-spoken register comparison candidate.",
    reviewerNote: "Confirm the MSA analysis and whether the form is noticeably formal in each reviewed café context.",
    scenarioIds: ["scenario-cairo-cafe", "scenario-abu-dhabi-cafe"],
    publicationStatus: "disabled",
  },
] as const satisfies readonly DialectVariant[];

export const crossDialectTransferRules = [
  {
    ...pendingLinguisticReview,
    id: "transfer-egyptian-to-emirati-order-coffee",
    conceptId: "concept-order-coffee",
    sourceVariantId: "variant-egyptian-want-coffee",
    targetVariantId: "variant-emirati-want-coffee",
    targetScenarioIds: ["scenario-abu-dhabi-cafe"],
    explanationKey: "guide.transfer.egyptian-emirati.order-coffee",
    reviewerNote: "Review both variety claims, pragmatic equivalence, café register, and learner-facing wording.",
    publicationStatus: "disabled",
  },
] as const satisfies readonly CrossDialectTransferRule[];
