import { pendingLinguisticReview } from "@/content/review-state";
import type { Scenario } from "@/domain/content/types";

export const scenarios = [
  {
    ...pendingLinguisticReview,
    id: "scenario-abu-dhabi-cafe",
    destinationId: "destination-abu-dhabi",
    targetDialectId: "emirati-abu-dhabi",
    characterId: "character-abu-dhabi-cafe-mariam",
    title: "A warm café order",
    setting: "cafe",
    availability: "available",
    environmentId: "environment-abu-dhabi-cafe",
    dialoguePackId: "dialogue-abu-dhabi-cafe",
    communicativeGoal: {
      en: "Greet Mariam, order a coffee, shape the order, and close politely.",
      ar: "رحّب بمريم، واطلب قهوة، وحدّد طلبك، واختتم بلطف.",
    },
    learningConceptIds: [
      "concept-greeting",
      "concept-order-coffee",
      "concept-drink-detail",
      "concept-polite-close",
    ],
    allowedVariantIds: [
      "variant-emirati-want-coffee",
      "variant-egyptian-want-coffee",
      "variant-msa-want-coffee",
    ],
  },
  {
    ...pendingLinguisticReview,
    id: "scenario-abu-dhabi-campus",
    destinationId: "destination-abu-dhabi",
    targetDialectId: "emirati-abu-dhabi",
    characterId: "character-abu-dhabi-campus-zayed",
    title: "Find your way on campus",
    setting: "campus",
    availability: "available",
    environmentId: "environment-abu-dhabi-campus",
    dialoguePackId: "dialogue-abu-dhabi-campus",
    communicativeGoal: {
      en: "Introduce yourself, ask for the library, and handle a short peer exchange.",
      ar: "عرّف بنفسك، واسأل عن المكتبة، وأكمل حديثاً قصيراً مع زميل.",
    },
    learningConceptIds: [
      "concept-greeting",
      "concept-introduce-self",
      "concept-find-place",
      "concept-class-time",
      "concept-study-subject",
      "concept-polite-close",
    ],
    allowedVariantIds: [],
  },
  {
    ...pendingLinguisticReview,
    id: "scenario-cairo-cafe",
    destinationId: "destination-cairo",
    targetDialectId: "egyptian-cairo",
    characterId: "character-cairo-cafe-nour",
    title: "A neighbourhood café order",
    setting: "cafe",
    availability: "available",
    environmentId: "environment-cairo-cafe",
    dialoguePackId: "dialogue-cairo-cafe",
    communicativeGoal: {
      en: "Order a coffee, answer quick choices, and close the exchange naturally.",
      ar: "اطلب قهوة، وأجب عن اختيارات سريعة، واختتم الحوار بشكل طبيعي.",
    },
    learningConceptIds: [
      "concept-greeting",
      "concept-order-coffee",
      "concept-drink-detail",
      "concept-polite-close",
    ],
    allowedVariantIds: ["variant-egyptian-want-coffee", "variant-msa-want-coffee"],
  },
  {
    ...pendingLinguisticReview,
    id: "scenario-cairo-transport",
    destinationId: "destination-cairo",
    targetDialectId: "egyptian-cairo",
    characterId: "character-cairo-taxi-hossam",
    title: "Across Cairo by taxi",
    setting: "transport",
    availability: "available",
    environmentId: "environment-cairo-taxi",
    dialoguePackId: "dialogue-cairo-taxi",
    communicativeGoal: {
      en: "State a destination, choose a route, check the fare, and stop in the right place.",
      ar: "اذكر وجهتك، واختر الطريق، وتحقق من الأجرة، وانزل في المكان المناسب.",
    },
    learningConceptIds: [
      "concept-greeting",
      "concept-state-destination",
      "concept-choose-route",
      "concept-describe-urgency",
      "concept-confirm-stop",
      "concept-understand-price",
      "concept-polite-close",
    ],
    allowedVariantIds: [],
  },
] as const satisfies readonly Scenario[];
