import type {
  AvailableScenarioHotspot,
  CameraPreset,
  DestinationArrival,
  FutureDestinationNode,
  ScenarioHotspot,
} from "@/domain/travel/types";

export const worldCameraPreset: CameraPreset = {
  center: [26, 23],
  zoom: 2.15,
  pitch: 0,
  bearing: 0,
};

export const destinationArrivals = [
  {
    destinationId: "destination-cairo",
    worldCamera: { center: [31.2357, 30.0444], zoom: 4.5, pitch: 8, bearing: 0 },
    cityCamera: { center: [31.2357, 30.0444], zoom: 13.35, pitch: 48, bearing: -14 },
    atmosphere: "river",
    introduction: {
      en: "Explore café, transport, and market situations across the city.",
      ar: "استكشف مواقف المقهى والمواصلات والتسوّق في أنحاء المدينة.",
    },
    validationStatus: "needs_review",
  },
  {
    destinationId: "destination-abu-dhabi",
    worldCamera: { center: [54.3773, 24.4539], zoom: 4.5, pitch: 8, bearing: 0 },
    cityCamera: { center: [54.3773, 24.4539], zoom: 13.4, pitch: 50, bearing: -22 },
    atmosphere: "coastal",
    introduction: {
      en: "Explore everyday communication situations across the city.",
      ar: "استكشف مواقف التواصل اليومية في أنحاء المدينة.",
    },
    validationStatus: "needs_review",
  },
  {
    destinationId: "destination-casablanca",
    worldCamera: { center: [-7.5898, 33.5731], zoom: 4.5, pitch: 8, bearing: 0 },
    cityCamera: { center: [-7.5898, 33.5731], zoom: 11.9, pitch: 38, bearing: 10 },
    atmosphere: "coastal",
    introduction: {
      en: "Part of MANARA's future network. City scenarios are not available yet.",
      ar: "جزء من شبكة منارة المستقبلية. مواقف المدينة غير متاحة بعد.",
    },
    validationStatus: "needs_review",
  },
] as const satisfies readonly DestinationArrival[];

export const scenarioHotspots = [
  {
    id: "hotspot-abu-dhabi-cafe",
    slug: "cafe",
    destinationId: "destination-abu-dhabi",
    scenarioId: "scenario-abu-dhabi-cafe",
    name: { en: "Café", ar: "المقهى" },
    kind: "cafe",
    availability: "available",
    coordinates: [54.3712, 24.4695],
    fallbackPosition: { inline: 35, block: 46 },
    camera: { center: [54.3712, 24.4695], zoom: 15.6, pitch: 58, bearing: -28 },
    objective: {
      en: "Order a coffee and complete the short interaction in Arabic.",
      ar: "اطلب قهوة وأكمل الموقف القصير باللغة العربية.",
    },
    validationStatus: "needs_review",
  },
  {
    id: "hotspot-abu-dhabi-majlis",
    slug: "majlis",
    destinationId: "destination-abu-dhabi",
    name: { en: "Majlis / Social visit", ar: "المجلس" },
    kind: "majlis",
    availability: "preview",
    coordinates: [54.393, 24.448],
    fallbackPosition: { inline: 66, block: 37 },
    camera: { center: [54.393, 24.448], zoom: 15.3, pitch: 56, bearing: 18 },
    objective: {
      en: "Preview a future greetings and hospitality scenario.",
      ar: "عاين موقفاً مستقبلياً للترحيب والضيافة.",
    },
    validationStatus: "needs_review",
  },
  {
    id: "hotspot-abu-dhabi-transport",
    slug: "transport",
    destinationId: "destination-abu-dhabi",
    name: { en: "Transport", ar: "المواصلات" },
    kind: "transport",
    availability: "coming_soon",
    coordinates: [54.382, 24.478],
    fallbackPosition: { inline: 58, block: 63 },
    camera: { center: [54.382, 24.478], zoom: 15.1, pitch: 52, bearing: 8 },
    objective: {
      en: "A future scenario for destinations, directions, and short exchanges.",
      ar: "موقف مستقبلي للوجهات والاتجاهات والتبادلات القصيرة.",
    },
    validationStatus: "needs_review",
  },
  {
    id: "hotspot-abu-dhabi-campus",
    slug: "campus",
    destinationId: "destination-abu-dhabi",
    scenarioId: "scenario-abu-dhabi-campus",
    name: { en: "University / Campus", ar: "الجامعة" },
    kind: "campus",
    availability: "available",
    coordinates: [54.404, 24.462],
    fallbackPosition: { inline: 73, block: 57 },
    camera: { center: [54.404, 24.462], zoom: 15.2, pitch: 54, bearing: -8 },
    objective: {
      en: "Find the library and complete a short peer conversation.",
      ar: "اعثر على المكتبة وأكمل حواراً قصيراً مع زميل.",
    },
    validationStatus: "needs_review",
  },
  {
    id: "hotspot-cairo-cafe",
    slug: "cafe",
    destinationId: "destination-cairo",
    scenarioId: "scenario-cairo-cafe",
    name: { en: "Café", ar: "المقهى" },
    kind: "cafe",
    availability: "available",
    coordinates: [31.2324, 30.0476],
    fallbackPosition: { inline: 38, block: 42 },
    camera: { center: [31.2324, 30.0476], zoom: 15.55, pitch: 56, bearing: 18 },
    objective: {
      en: "Order a coffee and complete the short interaction in Arabic.",
      ar: "اطلب قهوة وأكمل الموقف القصير باللغة العربية.",
    },
    validationStatus: "needs_review",
  },
  {
    id: "hotspot-cairo-transport",
    slug: "transport",
    destinationId: "destination-cairo",
    scenarioId: "scenario-cairo-transport",
    name: { en: "Taxi / Transport", ar: "المواصلات" },
    kind: "transport",
    availability: "available",
    coordinates: [31.246, 30.052],
    fallbackPosition: { inline: 65, block: 55 },
    camera: { center: [31.246, 30.052], zoom: 15.2, pitch: 52, bearing: -12 },
    objective: {
      en: "Take a taxi, confirm the route and fare, and arrive at your stop.",
      ar: "استقل سيارة أجرة، وأكد الطريق والأجرة، ووصل إلى محطتك.",
    },
    validationStatus: "needs_review",
  },
  {
    id: "hotspot-cairo-market",
    slug: "market",
    destinationId: "destination-cairo",
    name: { en: "Market / Shopping", ar: "التسوّق" },
    kind: "market",
    availability: "coming_soon",
    coordinates: [31.258, 30.045],
    fallbackPosition: { inline: 72, block: 32 },
    camera: { center: [31.258, 30.045], zoom: 15.35, pitch: 55, bearing: 24 },
    objective: {
      en: "A future scenario for prices, quantities, and short exchanges.",
      ar: "موقف مستقبلي للأسعار والكميات والتبادلات القصيرة.",
    },
    validationStatus: "needs_review",
  },
] as const satisfies readonly ScenarioHotspot[];

export const futureDestinationNodes = [
  {
    id: "future-dubai",
    name: { en: "Dubai", ar: "دبي" },
    countryName: { en: "United Arab Emirates", ar: "الإمارات العربية المتحدة" },
    coordinates: [55.2708, 25.2048],
    labelPriority: 520,
    availability: "future",
    validationStatus: "needs_review",
  },
  {
    id: "future-sharjah",
    name: { en: "Sharjah", ar: "الشارقة" },
    countryName: { en: "United Arab Emirates", ar: "الإمارات العربية المتحدة" },
    coordinates: [55.4033, 25.3463],
    labelPriority: 360,
    availability: "future",
    validationStatus: "needs_review",
  },
  {
    id: "future-al-ain",
    name: { en: "Al Ain", ar: "العين" },
    countryName: { en: "United Arab Emirates", ar: "الإمارات العربية المتحدة" },
    coordinates: [55.7606, 24.1302],
    labelPriority: 350,
    availability: "future",
    validationStatus: "needs_review",
  },
  {
    id: "future-riyadh",
    name: { en: "Riyadh", ar: "الرياض" },
    countryName: { en: "Saudi Arabia", ar: "المملكة العربية السعودية" },
    coordinates: [46.6753, 24.7136],
    labelPriority: 760,
    availability: "future",
    validationStatus: "needs_review",
  },
  {
    id: "future-jeddah",
    name: { en: "Jeddah", ar: "جدة" },
    countryName: { en: "Saudi Arabia", ar: "المملكة العربية السعودية" },
    coordinates: [39.1925, 21.4858],
    labelPriority: 660,
    availability: "future",
    validationStatus: "needs_review",
  },
  {
    id: "future-medina",
    name: { en: "Medina", ar: "المدينة المنورة" },
    countryName: { en: "Saudi Arabia", ar: "المملكة العربية السعودية" },
    coordinates: [39.5692, 24.5247],
    labelPriority: 470,
    availability: "future",
    validationStatus: "needs_review",
  },
  {
    id: "future-dammam",
    name: { en: "Dammam", ar: "الدمام" },
    countryName: { en: "Saudi Arabia", ar: "المملكة العربية السعودية" },
    coordinates: [50.0888, 26.4207],
    labelPriority: 450,
    availability: "future",
    validationStatus: "needs_review",
  },
  {
    id: "future-doha",
    name: { en: "Doha", ar: "الدوحة" },
    countryName: { en: "Qatar", ar: "قطر" },
    coordinates: [51.531, 25.2854],
    labelPriority: 700,
    availability: "future",
    validationStatus: "needs_review",
  },
  {
    id: "future-kuwait-city",
    name: { en: "Kuwait City", ar: "مدينة الكويت" },
    countryName: { en: "Kuwait", ar: "الكويت" },
    coordinates: [47.9774, 29.3759],
    labelPriority: 630,
    availability: "future",
    validationStatus: "needs_review",
  },
  {
    id: "future-manama",
    name: { en: "Manama", ar: "المنامة" },
    countryName: { en: "Bahrain", ar: "البحرين" },
    coordinates: [50.586, 26.2285],
    labelPriority: 560,
    availability: "future",
    validationStatus: "needs_review",
  },
  {
    id: "future-muscat",
    name: { en: "Muscat", ar: "مسقط" },
    countryName: { en: "Oman", ar: "عُمان" },
    coordinates: [58.4059, 23.588],
    labelPriority: 650,
    availability: "future",
    validationStatus: "needs_review",
  },
  {
    id: "future-salalah",
    name: { en: "Salalah", ar: "صلالة" },
    countryName: { en: "Oman", ar: "عُمان" },
    coordinates: [54.0924, 17.0197],
    labelPriority: 350,
    availability: "future",
    validationStatus: "needs_review",
  },
  {
    id: "future-amman",
    name: { en: "Amman", ar: "عمّان" },
    countryName: { en: "Jordan", ar: "الأردن" },
    coordinates: [35.9106, 31.9539],
    labelPriority: 740,
    availability: "future",
    validationStatus: "needs_review",
  },
  {
    id: "future-beirut",
    name: { en: "Beirut", ar: "بيروت" },
    countryName: { en: "Lebanon", ar: "لبنان" },
    coordinates: [35.5018, 33.8938],
    labelPriority: 720,
    availability: "future",
    validationStatus: "needs_review",
  },
  {
    id: "future-damascus",
    name: { en: "Damascus", ar: "دمشق" },
    countryName: { en: "Syria", ar: "سوريا" },
    coordinates: [36.2765, 33.5138],
    labelPriority: 590,
    availability: "future",
    validationStatus: "needs_review",
  },
  {
    id: "future-aleppo",
    name: { en: "Aleppo", ar: "حلب" },
    countryName: { en: "Syria", ar: "سوريا" },
    coordinates: [37.1343, 36.2021],
    labelPriority: 430,
    availability: "future",
    validationStatus: "needs_review",
  },
  {
    id: "future-ramallah",
    name: { en: "Ramallah", ar: "رام الله" },
    countryName: { en: "Palestine", ar: "فلسطين" },
    coordinates: [35.2034, 31.9038],
    labelPriority: 460,
    availability: "future",
    validationStatus: "needs_review",
  },
  {
    id: "future-jerusalem",
    name: { en: "Jerusalem", ar: "القدس" },
    countryName: { en: "Palestine", ar: "فلسطين" },
    coordinates: [35.2137, 31.7683],
    labelPriority: 610,
    availability: "future",
    validationStatus: "needs_review",
  },
  {
    id: "future-baghdad",
    name: { en: "Baghdad", ar: "بغداد" },
    countryName: { en: "Iraq", ar: "العراق" },
    coordinates: [44.3661, 33.3152],
    labelPriority: 710,
    availability: "future",
    validationStatus: "needs_review",
  },
  {
    id: "future-basra",
    name: { en: "Basra", ar: "البصرة" },
    countryName: { en: "Iraq", ar: "العراق" },
    coordinates: [47.7804, 30.5085],
    labelPriority: 420,
    availability: "future",
    validationStatus: "needs_review",
  },
  {
    id: "future-alexandria",
    name: { en: "Alexandria", ar: "الإسكندرية" },
    countryName: { en: "Egypt", ar: "مصر" },
    coordinates: [29.9187, 31.2001],
    labelPriority: 680,
    availability: "future",
    validationStatus: "needs_review",
  },
  {
    id: "future-aswan",
    name: { en: "Aswan", ar: "أسوان" },
    countryName: { en: "Egypt", ar: "مصر" },
    coordinates: [32.8998, 24.0889],
    labelPriority: 390,
    availability: "future",
    validationStatus: "needs_review",
  },
  {
    id: "future-tunis",
    name: { en: "Tunis", ar: "تونس" },
    countryName: { en: "Tunisia", ar: "تونس" },
    coordinates: [10.1815, 36.8065],
    labelPriority: 690,
    availability: "future",
    validationStatus: "needs_review",
  },
  {
    id: "future-sfax",
    name: { en: "Sfax", ar: "صفاقس" },
    countryName: { en: "Tunisia", ar: "تونس" },
    coordinates: [10.7603, 34.7406],
    labelPriority: 340,
    availability: "future",
    validationStatus: "needs_review",
  },
  {
    id: "future-algiers",
    name: { en: "Algiers", ar: "الجزائر" },
    countryName: { en: "Algeria", ar: "الجزائر" },
    coordinates: [3.0588, 36.7538],
    labelPriority: 670,
    availability: "future",
    validationStatus: "needs_review",
  },
  {
    id: "future-oran",
    name: { en: "Oran", ar: "وهران" },
    countryName: { en: "Algeria", ar: "الجزائر" },
    coordinates: [-0.6417, 35.6971],
    labelPriority: 380,
    availability: "future",
    validationStatus: "needs_review",
  },
  {
    id: "future-rabat",
    name: { en: "Rabat", ar: "الرباط" },
    countryName: { en: "Morocco", ar: "المغرب" },
    coordinates: [-6.8498, 34.0209],
    labelPriority: 640,
    availability: "future",
    validationStatus: "needs_review",
  },
  {
    id: "future-marrakech",
    name: { en: "Marrakech", ar: "مراكش" },
    countryName: { en: "Morocco", ar: "المغرب" },
    coordinates: [-7.9811, 31.6295],
    labelPriority: 520,
    availability: "future",
    validationStatus: "needs_review",
  },
  {
    id: "future-fez",
    name: { en: "Fez", ar: "فاس" },
    countryName: { en: "Morocco", ar: "المغرب" },
    coordinates: [-5.0078, 34.0181],
    labelPriority: 430,
    availability: "future",
    validationStatus: "needs_review",
  },
  {
    id: "future-tangier",
    name: { en: "Tangier", ar: "طنجة" },
    countryName: { en: "Morocco", ar: "المغرب" },
    coordinates: [-5.8128, 35.7595],
    labelPriority: 480,
    availability: "future",
    validationStatus: "needs_review",
  },
  {
    id: "future-tripoli",
    name: { en: "Tripoli", ar: "طرابلس" },
    countryName: { en: "Libya", ar: "ليبيا" },
    coordinates: [13.1913, 32.8872],
    labelPriority: 600,
    availability: "future",
    validationStatus: "needs_review",
  },
  {
    id: "future-benghazi",
    name: { en: "Benghazi", ar: "بنغازي" },
    countryName: { en: "Libya", ar: "ليبيا" },
    coordinates: [20.0667, 32.1167],
    labelPriority: 440,
    availability: "future",
    validationStatus: "needs_review",
  },
  {
    id: "future-khartoum",
    name: { en: "Khartoum", ar: "الخرطوم" },
    countryName: { en: "Sudan", ar: "السودان" },
    coordinates: [32.5599, 15.5007],
    labelPriority: 620,
    availability: "future",
    validationStatus: "needs_review",
  },
  {
    id: "future-port-sudan",
    name: { en: "Port Sudan", ar: "بورتسودان" },
    countryName: { en: "Sudan", ar: "السودان" },
    coordinates: [37.2164, 19.6158],
    labelPriority: 340,
    availability: "future",
    validationStatus: "needs_review",
  },
  {
    id: "future-sanaa",
    name: { en: "Sana'a", ar: "صنعاء" },
    countryName: { en: "Yemen", ar: "اليمن" },
    coordinates: [44.2075, 15.3694],
    labelPriority: 580,
    availability: "future",
    validationStatus: "needs_review",
  },
  {
    id: "future-aden",
    name: { en: "Aden", ar: "عدن" },
    countryName: { en: "Yemen", ar: "اليمن" },
    coordinates: [45.0367, 12.7855],
    labelPriority: 410,
    availability: "future",
    validationStatus: "needs_review",
  },
] as const satisfies readonly FutureDestinationNode[];

export function getDestinationArrival(destinationId: string) {
  return destinationArrivals.find((arrival) => arrival.destinationId === destinationId);
}

export function getDestinationHotspots(destinationId: string) {
  return scenarioHotspots.filter((hotspot) => hotspot.destinationId === destinationId);
}

export function getScenarioHotspot(
  destinationId: string,
  slug: string,
): AvailableScenarioHotspot | undefined {
  const hotspots: readonly ScenarioHotspot[] = scenarioHotspots;

  return hotspots.find(
    (hotspot): hotspot is AvailableScenarioHotspot =>
      hotspot.destinationId === destinationId &&
      hotspot.slug === slug &&
      hotspot.availability === "available",
  );
}
