import { pendingLinguisticReview as review } from "@/content/review-state";
import type { DialoguePack } from "@/domain/scenario/types";

export const abuDhabiCafeDialoguePack = {
  ...review,
  id: "dialogue-abu-dhabi-cafe",
  scenarioId: "scenario-abu-dhabi-cafe",
  characterId: "character-abu-dhabi-cafe-mariam",
  environmentId: "environment-abu-dhabi-cafe",
  title: { en: "Your order with Mariam", ar: "طلبك مع مريم" },
  startingBeatId: "adc-01-order",
  publicationStatus: "disabled",
  beats: [
    {
      ...review,
      id: "adc-01-order",
      scenarioId: "scenario-abu-dhabi-cafe",
      sequence: 1,
      characterLine: {
        ...review,
        id: "line-adc-01",
        scenarioId: "scenario-abu-dhabi-cafe",
        characterId: "character-abu-dhabi-cafe-mariam",
        speaker: "local_character",
        arabicText: "مرحبا، حيّاك. شو تحب تطلب؟",
        englishMeaning: "Hello, welcome. What would you like to order?",
        transliteration: "Marhaba, hayyak. Shu t-hibb titlub?",
        dialectOrRegister: "Proposed casual Emirati Arabic — Abu Dhabi",
        communicativeIntent: "welcome_and_invite_order",
        linguisticNotes: "Opens a first-time café exchange without over-teaching.",
        reviewerNote: "Confirm greeting sequence, verb form, addressee bounds, and natural café register.",
      },
      prompt: { en: "Order a coffee.", ar: "اطلب قهوة." },
      hint: { en: "Try: I want a coffee, please.", ar: "جرّب: أبغي قهوة لو سمحت." },
      vocabulary: [{ ...review, id: "vocab-adc-abghi", arabic: "أبغي", english: "I want", transliteration: "abghi", reviewerNote: "Confirm Emirati attribution and bounds in this context." }],
      responseOptions: [
        {
          ...review,
          id: "response-adc-01-target",
          scenarioId: "scenario-abu-dhabi-cafe",
          beatId: "adc-01-order",
          arabicText: "أبغي قهوة لو سمحت",
          englishMeaning: "I want a coffee, please.",
          transliteration: "Abghi gahwa law samaht.",
          dialectOrRegister: "Proposed casual Emirati Arabic — Abu Dhabi",
          communicativeIntent: "order_coffee",
          kind: "target_dialect",
          learningConceptId: "concept-order-coffee",
          variantId: "variant-emirati-want-coffee",
          nextBeatId: "adc-02-temperature",
          linguisticNotes: "Flagship target-context request candidate.",
          reviewerNote: "Confirm natural wording, politeness, phonological transliteration, and social bounds.",
        },
        {
          ...review,
          id: "response-adc-01-egyptian",
          scenarioId: "scenario-abu-dhabi-cafe",
          beatId: "adc-01-order",
          arabicText: "عايز قهوة لو سمحت",
          englishMeaning: "I want a coffee, please.",
          transliteration: "Ayiz ahwa law samaht.",
          dialectOrRegister: "Proposed Egyptian Arabic transfer candidate",
          communicativeIntent: "order_coffee",
          kind: "source_dialect",
          learningConceptId: "concept-order-coffee",
          variantId: "variant-egyptian-want-coffee",
          nextBeatId: "adc-02-temperature",
          linguisticNotes: "Canonical cross-dialect architecture case; not publishable until both sides and the mapping are verified.",
          reviewerNote: "Confirm Egyptian form, intelligibility in Abu Dhabi, transfer framing, and target alternative.",
        },
        {
          ...review,
          id: "response-adc-01-msa",
          scenarioId: "scenario-abu-dhabi-cafe",
          beatId: "adc-01-order",
          arabicText: "أريد قهوة من فضلك",
          englishMeaning: "I would like coffee, please.",
          transliteration: "Uridu qahwatan min fadlik.",
          dialectOrRegister: "Proposed Modern Standard Arabic / formal bridge",
          communicativeIntent: "order_coffee",
          kind: "msa",
          learningConceptId: "concept-order-coffee",
          variantId: "variant-msa-want-coffee",
          nextBeatId: "adc-02-temperature",
          linguisticNotes: "Provides a register-adaptation branch without framing MSA as wrong.",
          reviewerNote: "Confirm case-ending omission assumptions, register effect, and comparison wording.",
        },
      ],
    },
    {
      ...review,
      id: "adc-02-temperature",
      scenarioId: "scenario-abu-dhabi-cafe",
      sequence: 2,
      characterLine: {
        ...review, id: "line-adc-02", scenarioId: "scenario-abu-dhabi-cafe", characterId: "character-abu-dhabi-cafe-mariam", speaker: "local_character",
        arabicText: "أكيد. حارّة ولا باردة؟", englishMeaning: "Of course. Hot or cold?", transliteration: "Akeed. Harra wala barda?",
        dialectOrRegister: "Proposed casual Emirati Arabic — Abu Dhabi", communicativeIntent: "ask_drink_temperature",
        linguisticNotes: "A short service follow-up with a binary choice.", reviewerNote: "Confirm adjective forms and natural café delivery.",
      },
      prompt: { en: "Choose hot.", ar: "اختر الحار." },
      hint: { en: "Say: Hot, please.", ar: "قل: حارّة، لو سمحت." },
      vocabulary: [{ ...review, id: "vocab-adc-harra", arabic: "حارّة", english: "hot", transliteration: "harra", reviewerNote: "Confirm agreement with the understood drink noun." }],
      responseOptions: [{
        ...review, id: "response-adc-02", scenarioId: "scenario-abu-dhabi-cafe", beatId: "adc-02-temperature",
        arabicText: "حارّة، لو سمحت", englishMeaning: "Hot, please.", transliteration: "Harra, law samaht.",
        dialectOrRegister: "Proposed casual Emirati Arabic — Abu Dhabi", communicativeIntent: "choose_hot_drink", kind: "beginner_model",
        learningConceptId: "concept-drink-detail", nextBeatId: "adc-03-size", linguisticNotes: "Modeled beginner response.", reviewerNote: "Confirm natural ellipsis and politeness.",
      }],
    },
    {
      ...review,
      id: "adc-03-size",
      scenarioId: "scenario-abu-dhabi-cafe",
      sequence: 3,
      characterLine: {
        ...review, id: "line-adc-03", scenarioId: "scenario-abu-dhabi-cafe", characterId: "character-abu-dhabi-cafe-mariam", speaker: "local_character",
        arabicText: "أي حجم تفضّل؟", englishMeaning: "Which size do you prefer?", transliteration: "Ay hajm tfaddal?",
        dialectOrRegister: "Proposed neutral/casual Emirati café speech", communicativeIntent: "ask_drink_size",
        linguisticNotes: "Keeps the order moving with one compact question.", reviewerNote: "Confirm verb, register, and addressee-gender handling.",
      },
      prompt: { en: "Choose a medium.", ar: "اختر الحجم الوسط." },
      hint: { en: "Say: Medium, please.", ar: "قل: وسط، من فضلك." },
      vocabulary: [{ ...review, id: "vocab-adc-wasat", arabic: "وسط", english: "medium", transliteration: "wasat", reviewerNote: "Confirm café size terminology in Abu Dhabi." }],
      responseOptions: [{
        ...review, id: "response-adc-03", scenarioId: "scenario-abu-dhabi-cafe", beatId: "adc-03-size",
        arabicText: "وسط، من فضلك", englishMeaning: "Medium, please.", transliteration: "Wasat, min fadlik.",
        dialectOrRegister: "Proposed neutral everyday Arabic", communicativeIntent: "choose_medium_size", kind: "beginner_model",
        learningConceptId: "concept-drink-detail", nextBeatId: "adc-04-milk", linguisticNotes: "Simple size selection.", reviewerNote: "Confirm locally conventional size term and politeness.",
      }],
    },
    {
      ...review,
      id: "adc-04-milk",
      scenarioId: "scenario-abu-dhabi-cafe",
      sequence: 4,
      characterLine: {
        ...review, id: "line-adc-04", scenarioId: "scenario-abu-dhabi-cafe", characterId: "character-abu-dhabi-cafe-mariam", speaker: "local_character",
        arabicText: "تباها بحليب؟", englishMeaning: "Do you want it with milk?", transliteration: "Tbaha b-haleeb?",
        dialectOrRegister: "Proposed casual Emirati Arabic — Abu Dhabi", communicativeIntent: "ask_for_milk",
        linguisticNotes: "Introduces a reusable drink-detail question.", reviewerNote: "High-priority review: confirm form, segmentation, pronoun reference, and speaker/addressee bounds.",
      },
      prompt: { en: "Say yes, with a little milk.", ar: "قل نعم، مع قليل من الحليب." },
      hint: { en: "Try: Yes, a little milk.", ar: "جرّب: هيه، شوي حليب." },
      vocabulary: [{ ...review, id: "vocab-adc-shway", arabic: "شوي", english: "a little", transliteration: "shway", reviewerNote: "Confirm natural quantity phrasing in this order." }],
      responseOptions: [{
        ...review, id: "response-adc-04", scenarioId: "scenario-abu-dhabi-cafe", beatId: "adc-04-milk",
        arabicText: "هيه، شوي حليب", englishMeaning: "Yes, a little milk.", transliteration: "Heeh, shway haleeb.",
        dialectOrRegister: "Proposed casual Emirati Arabic — Abu Dhabi", communicativeIntent: "request_little_milk", kind: "beginner_model",
        learningConceptId: "concept-drink-detail", nextBeatId: "adc-05-anything-else", linguisticNotes: "Short affirmative order detail.", reviewerNote: "Confirm affirmative particle and natural noun phrase.",
      }],
    },
    {
      ...review,
      id: "adc-05-anything-else",
      scenarioId: "scenario-abu-dhabi-cafe",
      sequence: 5,
      characterLine: {
        ...review, id: "line-adc-05", scenarioId: "scenario-abu-dhabi-cafe", characterId: "character-abu-dhabi-cafe-mariam", speaker: "local_character",
        arabicText: "شي ثاني؟", englishMeaning: "Anything else?", transliteration: "Shay thani?",
        dialectOrRegister: "Proposed casual Emirati Arabic — Abu Dhabi", communicativeIntent: "offer_additional_item",
        linguisticNotes: "Creates a natural opportunity to decline politely.", reviewerNote: "Confirm everyday café naturalness and prosody.",
      },
      prompt: { en: "Decline politely.", ar: "ارفض بلطف." },
      hint: { en: "Say: No, thank you.", ar: "قل: لا، مشكورة." },
      vocabulary: [{ ...review, id: "vocab-adc-mashkoora", arabic: "مشكورة", english: "thank you (to a woman)", transliteration: "mashkoora", reviewerNote: "Confirm gendered address and suitability for this learner-character relationship." }],
      responseOptions: [{
        ...review, id: "response-adc-05", scenarioId: "scenario-abu-dhabi-cafe", beatId: "adc-05-anything-else",
        arabicText: "لا، مشكورة", englishMeaning: "No, thank you.", transliteration: "La, mashkoora.",
        dialectOrRegister: "Proposed casual Emirati Arabic — Abu Dhabi", communicativeIntent: "decline_additional_item", kind: "beginner_model",
        learningConceptId: "concept-polite-close", nextBeatId: "adc-06-close", linguisticNotes: "Polite decline addressed to Mariam.", reviewerNote: "Confirm gender marking and interpersonal naturalness.",
      }],
    },
    {
      ...review,
      id: "adc-06-close",
      scenarioId: "scenario-abu-dhabi-cafe",
      sequence: 6,
      isCompletionBeat: true,
      characterLine: {
        ...review, id: "line-adc-06", scenarioId: "scenario-abu-dhabi-cafe", characterId: "character-abu-dhabi-cafe-mariam", speaker: "local_character",
        arabicText: "خلاص، طلبك بيكون جاهز بعد شوي.", englishMeaning: "All set—your order will be ready shortly.", transliteration: "Khalas, talabik biykoon jahiz baad shway.",
        dialectOrRegister: "Proposed casual Emirati Arabic — Abu Dhabi", communicativeIntent: "confirm_order",
        linguisticNotes: "Closes the service exchange and signals completion.", reviewerNote: "Confirm future construction, pronouns, and café register.",
      },
      prompt: { en: "Thank Mariam and finish.", ar: "اشكر مريم واختتم." },
      hint: { en: "Say: Thank you for your help.", ar: "قل: يعطيج العافية." },
      vocabulary: [{ ...review, id: "vocab-adc-yaateech", arabic: "يعطيج العافية", english: "thank you / may God give you wellness (to a woman)", transliteration: "yaateech il-aafya", reviewerNote: "Confirm pragmatic meaning, gendered form, and appropriateness here." }],
      responseOptions: [{
        ...review, id: "response-adc-06", scenarioId: "scenario-abu-dhabi-cafe", beatId: "adc-06-close",
        arabicText: "يعطيج العافية", englishMeaning: "Thank you for your help.", transliteration: "Yaateech il-aafya.",
        dialectOrRegister: "Proposed Gulf/Emirati polite formula", communicativeIntent: "thank_and_close", kind: "beginner_model",
        learningConceptId: "concept-polite-close", completesScenario: true, linguisticNotes: "Scenario-closing courtesy formula.", reviewerNote: "Confirm Emirati usage and gendered pronunciation/transliteration.",
      }],
    },
  ],
} as const satisfies DialoguePack;
